<?php


/*--------------------------------------------------------------*/
/*                   Theme Functions Here                       */                      
/*--------------------------------------------------------------*/


//---Theme Setup Options - Functions and Hooks
include('includes/theme-setup.php');

//---Adds Shortcodes
include('includes/theme-shortcodes.php');

//---Add Widgets
include('includes/theme-widgets.php');

//---Add Home Page Meta
include('includes/listings_meta_boxes.php');


/*--------------------------------------------------------------*/
/*                   Your Functions Below                       */                      
/*--------------------------------------------------------------*/
























?>